import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.product.deleteMany();

  await prisma.product.createMany({
    data: [
      {
        title: "Apple iPhone 15",
        description: "Latest iPhone with A17 chip",
        price: 79999,
        originalPrice: 84999,
        discountPercent: 6,
        category: "Mobiles",
        brand: "Apple",
        rating: 4.6,
        reviews: 4180,
        stock: 20,
        images: [
          "https://images.unsplash.com/photo-1695048133142-1a20484d2569",
          "https://images.unsplash.com/photo-1512054502232-10a0a035d672",
          "https://images.unsplash.com/photo-1616348436168-de43ad0db179"
        ],
      },
      {
        title: "Samsung Galaxy S24",
        description: "Flagship Android phone",
        price: 69999,
        originalPrice: 74999,
        discountPercent: 7,
        category: "Mobiles",
        brand: "Samsung",
        rating: 4.5,
        reviews: 3120,
        stock: 15,
        images: [
          "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c",
          "https://images.unsplash.com/photo-1675452937281-24485562bd84"
        ],
      },
      {
        title: "Sony WH-1000XM5",
        description: "Noise cancelling headphones",
        price: 29999,
        originalPrice: 34999,
        discountPercent: 14,
        category: "Electronics",
        brand: "Sony",
        rating: 4.7,
        reviews: 9820,
        stock: 30,
        images: [
          "https://images.unsplash.com/photo-1583394838336-acd977736f90"
        ],
      },
      {
        title: "MacBook Air M2",
        description: "Lightweight powerful laptop",
        price: 114999,
        originalPrice: 124999,
        discountPercent: 8,
        category: "Laptops",
        brand: "Apple",
        rating: 4.8,
        reviews: 2210,
        stock: 10,
        images: [
          "https://images.unsplash.com/photo-1517336714731-489689fd1ca8"
        ],
      },
      {
        title: "Dyson V15 Detect",
        description: "Cordless vacuum cleaner with laser dust detection",
        price: 52900,
        originalPrice: 55900,
        discountPercent: 5,
        category: "Home",
        brand: "Dyson",
        rating: 4.8,
        reviews: 1240,
        stock: 15,
        images: ["https://images.unsplash.com/photo-1558317374-067fb5f30001"]
      },
      {
        title: "Nespresso Vertuo Next",
        description: "Coffee and espresso machine with aeroccino",
        price: 16500,
        originalPrice: 22000,
        discountPercent: 25,
        category: "Home",
        brand: "Nespresso",
        rating: 4.5,
        reviews: 3210,
        stock: 45,
        images: ["https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6"]
      },
      {
        title: "Philips Hue Smart Bulb Starter Kit",
        description: "Personal wireless lighting system with bridge",
        price: 12999,
        originalPrice: 15999,
        discountPercent: 19,
        category: "Home",
        brand: "Philips",
        rating: 4.6,
        reviews: 8400,
        stock: 60,
        images: ["https://images.unsplash.com/photo-1609595781706-90b0b3a832f1"]
      },
      {
        title: "Levoit Air Purifier Core 300",
        description: "True HEPA Filter for large rooms and allergens",
        price: 9500,
        originalPrice: 11999,
        discountPercent: 21,
        category: "Home",
        brand: "Levoit",
        rating: 4.7,
        reviews: 15200,
        stock: 100,
        images: ["https://images.unsplash.com/photo-1585771724684-38269d6639fd"]
      },
      {
        title: "Ring Video Doorbell 4",
        description: "Smart doorbell with 1080p HD video and two-way talk",
        price: 18999,
        originalPrice: 19999,
        discountPercent: 5,
        category: "Home",
        brand: "Ring",
        rating: 4.4,
        reviews: 5600,
        stock: 22,
        images: ["https://images.unsplash.com/photo-1558002038-1055907df827"]
      },
      {
        title: "Instant Pot Duo Plus",
        description: "9-in-1 Electric pressure cooker and slow cooker",
        price: 11499,
        originalPrice: 14500,
        discountPercent: 21,
        category: "Home",
        brand: "Instant Pot",
        rating: 4.9,
        reviews: 21000,
        stock: 55,
        images: ["https://images.unsplash.com/photo-1544233726-9f1d2b27be8b"]
      },
      {
        title: "Le Creuset Enameled Dutch Oven",
        description: "Cast iron 5.5 quart round signature pot",
        price: 32000,
        originalPrice: 38000,
        discountPercent: 16,
        category: "Home",
        brand: "Le Creuset",
        rating: 4.9,
        reviews: 4300,
        stock: 12,
        images: ["https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7"]
      },
      {
        title: "Tuft & Needle Adaptive Foam Pillow",
        description: "Cooling memory foam pillow for neck support",
        price: 6500,
        originalPrice: 7500,
        discountPercent: 13,
        category: "Home",
        brand: "Tuft & Needle",
        rating: 4.3,
        reviews: 2900,
        stock: 150,
        images: ["https://images.unsplash.com/photo-1584132967334-10e028bd69f7"]
      },
      {
        title: "Cosori Air Fryer Max XL",
        description: "5.8 quart oil-less cooker with 13 presets",
        price: 10999,
        originalPrice: 12999,
        discountPercent: 15,
        category: "Home",
        brand: "Cosori",
        rating: 4.7,
        reviews: 18450,
        stock: 38,
        images: ["https://images.unsplash.com/photo-1584269600519-112d071b35e6"]
      },
      {
        title: "Herman Miller Aeron Chair",
        description: "Ergonomic office chair with lumbar support",
        price: 145000,
        originalPrice: 160000,
        discountPercent: 9,
        category: "Home",
        brand: "Herman Miller",
        rating: 4.8,
        reviews: 1100,
        stock: 8,
        images: ["https://images.unsplash.com/photo-1505797149-43b0069ec26b"]
      },
      {
          title: "La Mer Crème de la Mer",
          description: "Ultra-rich moisturizing cream for skin transformation",
          price: 16000,
          originalPrice: 19000,
          discountPercent: 15,
          category: "Beauty",
          brand: "La Mer",
          rating: 4.8,
          reviews: 5200,
          stock: 12,
          images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be"]
        },
        {
          title: "Drunk Elephant T.L.C. Sukari Babyfacial",
          description: "AHA/BHA mask to resurface skin clarity and texture",
          price: 6800,
          originalPrice: 8500,
          discountPercent: 20,
          category: "Beauty",
          brand: "Drunk Elephant",
          rating: 4.7,
          reviews: 2492,
          stock: 25,
          images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03"]
        },
        {
          title: "Fenty Beauty Pro Filt'r Foundation",
          description: "Soft matte, longwear foundation in 50 inclusive shades",
          price: 3735,
          originalPrice: 4150,
          discountPercent: 10,
          category: "Beauty",
          brand: "Fenty Beauty",
          rating: 4.3,
          reviews: 20100,
          stock: 80,
          images: ["https://images.unsplash.com/photo-1627885793933-584e53987c14"]
        },
        {
          title: "The Ordinary Niacinamide 10% + Zinc 1%",
          description: "High-strength vitamin and mineral blemish formula",
          price: 600,
          originalPrice: 750,
          discountPercent: 20,
          category: "Beauty",
          brand: "The Ordinary",
          rating: 4.6,
          reviews: 4751,
          stock: 150,
          images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be"]
        },
        {
          title: "Charlotte Tilbury Magic Cream",
          description: "Award-winning moisturizer for instant glowing skin",
          price: 8200,
          originalPrice: 9500,
          discountPercent: 13,
          category: "Beauty",
          brand: "Charlotte Tilbury",
          rating: 4.9,
          reviews: 3100,
          stock: 18,
          images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b"]
        },
        {
          title: "Rare Beauty Soft Pinch Liquid Blush",
          description: "Weightless, long-lasting liquid blush for a healthy flush",
          price: 2100,
          originalPrice: 2400,
          discountPercent: 12,
          category: "Beauty",
          brand: "Rare Beauty",
          rating: 4.8,
          reviews: 15400,
          stock: 40,
          images: ["https://images.unsplash.com/photo-1625093525885-282384697917"]
        },
        {
          title: "Laneige Lip Sleeping Mask",
          description: "Leave-on lip mask that soothes and moisturizes overnight",
          price: 1450,
          originalPrice: 1850,
          discountPercent: 21,
          category: "Beauty",
          brand: "Laneige",
          rating: 4.7,
          reviews: 8900,
          stock: 110,
          images: ["https://images.unsplash.com/photo-1608248597279-f99d160bfcbc"]
        },
        {
          title: "Dior Addict Lip Glow Oil",
          description: "Nourishing glossy lip oil with cherry oil protection",
          price: 3800,
          originalPrice: 4200,
          discountPercent: 9,
          category: "Beauty",
          brand: "Dior",
          rating: 4.5,
          reviews: 1200,
          stock: 15,
          images: ["https://images.unsplash.com/photo-1625093742435-6fa192b6fb10"]
        },
        {
          title: "Glow Recipe Watermelon Glow Toner",
          description: "PHA and BHA pore-tightening treatment",
          price: 3200,
          originalPrice: 3600,
          discountPercent: 11,
          category: "Beauty",
          brand: "Glow Recipe",
          rating: 4.4,
          reviews: 5600,
          stock: 35,
          images: ["https://images.unsplash.com/photo-1616986953793-2e6159b78580"]
        },
        {
          title: "Estée Lauder Advanced Night Repair",
          description: "Synchronized Multi-Recovery Complex serum",
          price: 7900,
          originalPrice: 9200,
          discountPercent: 14,
          category: "Beauty",
          brand: "Estée Lauder",
          rating: 4.8,
          reviews: 7400,
          stock: 20,
          images: ["https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b"]
        },
        {
            title: "Fear of God Essentials Hoodie",
            description: "Relaxed fit heavyweight fleece hoodie in 'Cloud' grey",
            price: 8500,
            originalPrice: 10500,
            discountPercent: 19,
            category: "Fashion",
            brand: "Fear of God",
            rating: 4.8,
            reviews: 12400,
            stock: 45,
            images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7"]
          },
          {
            title: "Uniqlo Airism Quarter-Zip Pullover",
            description: "Functional everyday tech-wear with moisture-wicking fabric",
            price: 2990,
            originalPrice: 3490,
            discountPercent: 14,
            category: "Fashion",
            brand: "Uniqlo",
            rating: 4.7,
            reviews: 8200,
            stock: 120,
            images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea"]
          },
          {
            title: "Nike Dunk Low 'Panda'",
            description: "Classic black and white leather sneakers",
            price: 8295,
            originalPrice: 9995,
            discountPercent: 17,
            category: "Fashion",
            brand: "Nike",
            rating: 4.5,
            reviews: 45000,
            stock: 15,
            images: ["https://images.unsplash.com/photo-1600185365483-26d7a4cc7519"]
          },
          {
            title: "Levi's 501 Original Fit Jeans",
            description: "Timeless straight-leg denim with button fly",
            price: 4500,
            originalPrice: 5999,
            discountPercent: 25,
            category: "Fashion",
            brand: "Levi's",
            rating: 4.6,
            reviews: 18300,
            stock: 60,
            images: ["https://images.unsplash.com/photo-1542272604-787c3835535d"]
          },
          {
            title: "Alo Yoga High-Waist Airlift Legging",
            description: "Premium studio-to-street performance leggings",
            price: 9800,
            originalPrice: 11500,
            discountPercent: 15,
            category: "Fashion",
            brand: "Alo Yoga",
            rating: 4.9,
            reviews: 6700,
            stock: 32,
            images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8"]
          },
          {
            title: "Zara Oversized Wool Blend Coat",
            description: "Double-breasted funnel neck winter coat",
            price: 12990,
            originalPrice: 15990,
            discountPercent: 19,
            category: "Fashion",
            brand: "Zara",
            rating: 4.2,
            reviews: 2100,
            stock: 20,
            images: ["https://images.unsplash.com/photo-1539533018447-63fcce2678e3"]
          },
          {
            title: "Ray-Ban Reverse Wayfarer",
            description: "Iconic sunglasses with innovative concave lenses",
            price: 14500,
            originalPrice: 16500,
            discountPercent: 12,
            category: "Fashion",
            brand: "Ray-Ban",
            rating: 4.7,
            reviews: 3400,
            stock: 25,
            images: ["https://images.unsplash.com/photo-1512099053734-e6767b535838"]
          },
          {
            title: "Aurelia Zari Work Kurta Set",
            description: "Festive ethnic wear with Mandarin collar and matching palazzos",
            price: 3060,
            originalPrice: 4500,
            discountPercent: 32,
            category: "Fashion",
            brand: "Aurelia",
            rating: 4.5,
            reviews: 1500,
            stock: 50,
            images: ["https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b"]
          },
          {
            title: "Patagonia Better Sweater Jacket",
            description: "Eco-friendly recycled polyester fleece jacket",
            price: 11000,
            originalPrice: 13000,
            discountPercent: 15,
            category: "Fashion",
            brand: "Patagonia",
            rating: 4.8,
            reviews: 9200,
            stock: 18,
            images: ["https://images.unsplash.com/photo-1603400521630-9f2de124b33b"]
          },
          {
            title: "Birkenstock Boston Clog",
            description: "Suede leather slip-ons with anatomically shaped footbed",
            price: 12500,
            originalPrice: 14500,
            discountPercent: 14,
            category: "Fashion",
            brand: "Birkenstock",
            rating: 4.7,
            reviews: 11200,
            stock: 8,
            images: ["https://images.unsplash.com/photo-1603623898166-be443d286cfa"]
          },
          {
            title: "Blue Tokai Roasted Coffee Beans",
            description: "Vienna Roast (Dark) - 250g Arabica beans",
            price: 540,
            originalPrice: 600,
            discountPercent: 10,
            category: "Grocery",
            brand: "Blue Tokai",
            rating: 4.8,
            reviews: 1250,
            stock: 40,
            images: ["https://images.unsplash.com/photo-1559056199-641a0ac8b55e"]
          },
          {
            title: "Epigamia Greek Yogurt (Pack of 4)",
            description: "Natural high-protein yogurt with no added sugar",
            price: 240,
            originalPrice: 280,
            discountPercent: 14,
            category: "Grocery",
            brand: "Epigamia",
            rating: 4.6,
            reviews: 3200,
            stock: 25,
            images: ["https://images.unsplash.com/photo-1488477181946-6428a0291777"]
          },
          {
            title: "Daawat Rozana Gold Basmati Rice",
            description: "Premium long-grain aged rice - 5kg",
            price: 495,
            originalPrice: 650,
            discountPercent: 24,
            category: "Grocery",
            brand: "Daawat",
            rating: 4.4,
            reviews: 8900,
            stock: 100,
            images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c"]
          },
          {
            title: "Himalayan Native Cow Ghee",
            description: "Pure A2 Desi Cow Ghee - 500ml glass jar",
            price: 899,
            originalPrice: 1100,
            discountPercent: 18,
            category: "Grocery",
            brand: "Himalayan Natives",
            rating: 4.9,
            reviews: 2100,
            stock: 35,
            images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae"]
          },
          {
            title: "Yoga Bar Multigrain Muesli",
            description: "Almond and Dark Chocolate energy muesli - 750g",
            price: 425,
            originalPrice: 550,
            discountPercent: 23,
            category: "Grocery",
            brand: "Yoga Bar",
            rating: 4.7,
            reviews: 5400,
            stock: 60,
            images: ["https://images.unsplash.com/photo-1517673132405-a56a62b18caf"]
          },
          {
            title: "Ferrero Rocher Hazelnut Chocolates",
            description: "Premium gift box - 24 pieces (300g)",
            price: 849,
            originalPrice: 995,
            discountPercent: 15,
            category: "Grocery",
            brand: "Ferrero",
            rating: 4.9,
            reviews: 15600,
            stock: 15,
            images: ["https://images.unsplash.com/photo-1549007994-cb92caebd54b"]
          },
          {
            title: "Happilo Premium Pistachios",
            description: "Roasted and Salted Californian Pistachios - 200g",
            price: 350,
            originalPrice: 425,
            discountPercent: 18,
            category: "Grocery",
            brand: "Happilo",
            rating: 4.5,
            reviews: 7800,
            stock: 80,
            images: ["https://images.unsplash.com/photo-1527324688151-0e627063f2b1"]
          },
          {
            title: "Tetley Green Tea (Lemon & Honey)",
            description: "Anti-oxidant rich green tea - 100 tea bags",
            price: 450,
            originalPrice: 520,
            discountPercent: 13,
            category: "Grocery",
            brand: "Tetley",
            rating: 4.6,
            reviews: 11200,
            stock: 120,
            images: ["https://images.unsplash.com/photo-1597481499750-3e6b22637e12"]
          },
          {
            title: "Organic India Tulsi Honey",
            description: "Pure wild forest honey with Tulsi extracts - 250g",
            price: 295,
            originalPrice: 325,
            discountPercent: 9,
            category: "Grocery",
            brand: "Organic India",
            rating: 4.4,
            reviews: 1800,
            stock: 55,
            images: ["https://images.unsplash.com/photo-1587049352846-4a222e784d38"]
          },
          {
            title: "Borges Extra Virgin Olive Oil",
            description: "Cold-pressed olive oil for dressings and health - 1L",
            price: 1150,
            originalPrice: 1499,
            discountPercent: 23,
            category: "Grocery",
            brand: "Borges",
            rating: 4.7,
            reviews: 9400,
            stock: 28,
            images: ["https://images.unsplash.com/photo-1763812770943-0b76492a38f0"]
          },
          {
              title: "Apple MacBook Air M3",
              description: "13.6-inch Liquid Retina Display, 8GB RAM, 256GB SSD",
              price: 114900,
              originalPrice: 119900,
              discountPercent: 4,
              category: "Electronics",
              brand: "Apple",
              rating: 4.9,
              reviews: 1250,
              stock: 12,
              images: ["https://images.unsplash.com/photo-1710905018864-d585574d79f8"]
            },
            {
              title: "Samsung Galaxy S24 Ultra",
              description: "Titanium Gray, 256GB Storage, AI-powered camera features",
              price: 129999,
              originalPrice: 134999,
              discountPercent: 4,
              category: "Electronics",
              brand: "Samsung",
              rating: 4.8,
              reviews: 5400,
              stock: 20,
              images: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf"]
            },
            {
              title: "Kindle Paperwhite (16 GB)",
              description: "6.8-inch display with adjustable warm light and waterproof design",
              price: 13999,
              originalPrice: 14999,
              discountPercent: 7,
              category: "Electronics",
              brand: "Amazon",
              rating: 4.7,
              reviews: 18200,
              stock: 55,
              images: ["https://images.unsplash.com/photo-1603406136476-85d8c3ec76a5"]
            },
            {
              title: "Sony PlayStation 5 Slim",
              description: "Ultra-High Speed SSD for lightning fast loading times",
              price: 44990,
              originalPrice: 54990,
              discountPercent: 18,
              category: "Electronics",
              brand: "Sony",
              rating: 4.9,
              reviews: 28400,
              stock: 5,
              images: ["https://images.unsplash.com/photo-1606144042614-b2417e99c4e3"]
            },
            {
              title: "Logitech MX Master 3S",
              description: "Wireless performance mouse with ultra-fast scrolling",
              price: 9495,
              originalPrice: 10995,
              discountPercent: 14,
              category: "Electronics",
              brand: "Logitech",
              rating: 4.8,
              reviews: 9500,
              stock: 42,
              images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46"]
            },
            {
              title: "Marshall Emberton II",
              description: "Portable Bluetooth speaker with 30+ hours of playtime",
              price: 14999,
              originalPrice: 17999,
              discountPercent: 17,
              category: "Electronics",
              brand: "Marshall",
              rating: 4.7,
              reviews: 3100,
              stock: 18,
              images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d"]
            },
            {
              title: "GoPro HERO12 Black",
              description: "Waterproof action camera with 5.3K60 Ultra HD video",
              price: 37500,
              originalPrice: 45000,
              discountPercent: 17,
              category: "Electronics",
              brand: "GoPro",
              rating: 4.6,
              reviews: 4200,
              stock: 25,
              images: ["https://images.unsplash.com/photo-1604942177421-df466b7410f6"]
            },
            {
              title: "Dell UltraSharp 27 4K Monitor",
              description: "USB-C Hub monitor with 98% DCI-P3 color coverage",
              price: 58900,
              originalPrice: 72000,
              discountPercent: 18,
              category: "Electronics",
              brand: "Dell",
              rating: 4.5,
              reviews: 1100,
              stock: 10,
              images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf"]
            },
            {
              title: "Seagate Expansion 2TB HDD",
              description: "External hard drive for PC, Mac, and PlayStation",
              price: 5999,
              originalPrice: 7999,
              discountPercent: 25,
              category: "Electronics",
              brand: "Seagate",
              rating: 4.4,
              reviews: 45000,
              stock: 85,
              images: ["https://images.unsplash.com/photo-1624895608078-e9f564cbe3fa"]
            },
            {
              title: "Apple Watch Series 9",
              description: "GPS 41mm Midnight Aluminum Case with Sport Band",
              price: 39900,
              originalPrice: 41900,
              discountPercent: 5,
              category: "Electronics",
              brand: "Apple",
              rating: 4.8,
              reviews: 8600,
              stock: 30,
              images: ["https://images.unsplash.com/photo-1546868871-7041f2a55e12"]
            }
    ],
  });

  console.log("✅ Products seeded with working images");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
